version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_tutor
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
